export enum TabScreens {
  HOME = 'Home',
  ORDER = 'Order',
  PROFILE = 'Profile',
  WISHLIST = 'Wishlist',
  CATEGORIES = 'Categories',
}

export enum Routes {
  FAQ = '/FAQ',
  HOME = '/home',
  SHOP = '/shop',
  ORDER = '/order',
  ONBOARDING = '/',
  FILTER = '/filter',
  SIGN_IN = '/sign-in',
  PRODUCT = '/product',
  SIGN_UP = '/sign-up',
  REVIEWS = '/reviews',
  PROFILE = '/profile',
  CHECKOUT = '/checkout',
  WISHLIST = '/wishlist',
  CATEGORIES = '/categories',
  INFO_SAVED = '/info-saved',
  CART_EMPTY = '/cart-empty',
  DESCRIPTION = '/description',
  EDIT_PROFILE = '/edit-profile',
  VERIFICATION = '/verification',
  ORDER_FAILED = '/order-failed',
  NEW_PASSWORD = '/new-password',
  MY_PROMOCODES = '/my-promocodes',
  ORDER_HISTORY = '/order-history',
  WISHLIST_EMPTY = '/wishlist-empty',
  EMAIL_VERIFIED = '/email-verified',
  PHONE_VERIFIED = '/phone-verified',
  LEAVE_A_REVIEW = '/leave-a-review',
  FORGOT_PASSWORD = '/forgot-password',
  ORDER_SUCCESSFUL = '/order-successful',
  PROMOCODES_EMPTY = '/promocodes-empty',
  TRACK_YOUR_ORDER = '/track-your-order',
  VERIFY_YOUR_EMAIL = '/verify-your-email',
  ORDER_HISTORY_EMPTY = '/order-history-empty',
  SIGN_UP_ACCOUNT_CREATED = '/sign-up-account-created',
  VERIFY_YOUR_PHONE_NUMBER = '/verify-your-phone-number',
  SHIPPING_AND_PAYMENT_INFO = '/shipping-and-payment-info',
  FORGOT_PASSWORD_SENT_EMAIL = '/forgot-password-sent-email',
}
